from .base import BaseDialect


class PostgresDialect(BaseDialect):
    name = "postgresql"
    placeholder = "%s"
    auto_increment = "GENERATED BY DEFAULT AS IDENTITY"
    supports_insert_returning = True
    type_map = {
        "integer": "INTEGER",
        "string": "VARCHAR",
        "text": "TEXT",
        "boolean": "BOOLEAN",
        "datetime": "TIMESTAMP",
        "float": "DOUBLE PRECISION",
        "decimal": "DECIMAL",
        "uuid": "UUID",
    }

    def auto_primary_key_sql(self):
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

    def literal(self, value):
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        return super().literal(value)

    def migration_history_table_sql(self, table="nexorm_migrations"):
        return (
            f"CREATE TABLE IF NOT EXISTS {self.quote_identifier(table)} ("
            f"{self.quote_identifier('id')} {self.auto_primary_key_sql()}, "
            f"{self.quote_identifier('name')} VARCHAR(255) NOT NULL UNIQUE, "
            f"{self.quote_identifier('applied_at')} TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
        )
